name: Push To Windows VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Copy files to host directory
        shell: cmd
        run: powershell -NoProfile -NonInteractive -Command "Copy-Item -Path 'C:\Users\Marwan\actions-runner\DDD_ContiniuousDeployment*' -Destination 'C:\inetpub\wwwroot' -Force"
