name: Push To Windows VM

on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: copy to host directory
        run:  powershell Copy-Item -Path C:\Users\Marwan\actions-runner\_work\DDD_ContiniuousDeployment* -Destination C:\inetpub\wwwroot -force -force

  
